# Generated by Django 6.0.7 on 2026-08-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='condition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
